// src/services/geminiService.ts
import { GoogleGenerativeAI } from "@google/generative-ai"; // Older SDK for text
import { GoogleGenAI } from "@google/genai"; // New SDK for Imagen 3
import { env } from "@/config/env";

const genAI = new GoogleGenerativeAI(env.GEMINI_API_KEY);
const imagenClient = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

interface RefinementInput {
  segment: string;
  style: string;
  model: string;
  background: string;
  directorNotes?: string;
  garmentImageUrl?: string;
}

export const geminiService = {
  /**
   * Transforms structured selections into a high-fidelity photographic prompt.
   */
  async refinePrompt(input: RefinementInput): Promise<string> {
    try {
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

      const systemPrompt = `
        You are an expert Fashion Creative Director.
        Create a professional photographic prompt for a fashion shoot.
        Product: ${input.segment} ${input.style}
        Model: ${input.model}
        Background: ${input.background}
        Extra Notes: ${input.directorNotes || "None"}

        The output should be a single paragraph focusing on lighting, composition, and high-end fashion aesthetics.
      `;

      const result = await model.generateContent(systemPrompt);
      const response = await result.response;
      return response.text().trim();
    } catch (error) {
      console.error("❌ [geminiService] Error refining prompt:", error);
      return `${input.segment} ${input.style} on a ${input.model} model, ${input.background} background.`;
    }
  },

  /**
   * Generates a high-fidelity image using Google Imagen 3.
   */
  async generateImage(input: RefinementInput): Promise<string> {
    try {
      // 1. Get a refined prompt first
      const professionalPrompt = await this.refinePrompt(input);
      console.log("🎨 [geminiService] Generated Prompt:", professionalPrompt);

      // 2. Trigger Imagen 3
      const response = await imagenClient.models.generateImages({
        model: "imagen-3.0-generate-001",
        prompt: professionalPrompt,
        config: {
          numberOfImages: 1,
          aspectRatio: "3:4", // Standard for fashion
        },
      });

      const generatedImage = response.generatedImages[0];
      if (!generatedImage || !generatedImage.image) {
        throw new Error("No image was generated by Gemini.");
      }

      // 3. Return as Base64 (or upload to a CDN if needed)
      // The SDK returns a base64 string usually if not using a specific output mode
      const base64Image = `data:image/png;base64,${generatedImage.image.imageBytes}`;
      console.log("✅ [geminiService] Image generated successfully");
      
      return base64Image;
    } catch (error: any) {
      console.error("❌ [geminiService] generateImage Error:", error);
      throw new Error(`Gemini Image Generation Failed: ${error.message}`);
    }
  }
};
